import type {
  Application,
  BrandingSettings,
  ConsoleState,
  Group,
  Person,
  ServiceAccount,
} from "./domain";
import { defaultDashboardConfig } from "./domain";

export const defaultBranding: BrandingSettings = {
  companyName: "Kanidm Dashboard",
  logoUrl: "",
  loginMessage: "Sign in to continue to your company applications and identity settings.",
  poweredBy: true,
  canManageNativeDomainBranding: true,
  theme: defaultDashboardConfig.theme,
};

export const seedPeople: Person[] = [
  {
    id: "u-ava",
    username: "ava",
    displayName: "Ava Chen",
    legalName: "Ava Chen",
    email: "ava@aster.example",
    status: "active",
    groups: ["g-engineering", "g-admins", "g-grafana"],
    credential: {
      password: "healthy",
      passkeys: 2,
      totp: true,
      backupCodes: 8,
      unixCredential: true,
      sshKeys: 3,
      radiusPassword: true,
    },
    unix: {
      gidNumber: 10001,
      shell: "/bin/zsh",
      credentialSet: true,
    },
    lastAuth: "2026-05-29 09:12",
  },
  {
    id: "u-mika",
    username: "mika",
    displayName: "Mika Patel",
    legalName: "Mika Patel",
    email: "mika@aster.example",
    status: "active",
    groups: ["g-engineering", "g-grafana", "g-gitea"],
    credential: {
      password: "healthy",
      passkeys: 1,
      totp: true,
      backupCodes: 10,
      unixCredential: true,
      sshKeys: 2,
      radiusPassword: false,
    },
    unix: {
      gidNumber: 10002,
      shell: "/bin/bash",
      credentialSet: true,
    },
    lastAuth: "2026-05-29 08:43",
  },
  {
    id: "u-rin",
    username: "rin",
    displayName: "Rin Morales",
    legalName: "Rin Morales",
    email: "rin@aster.example",
    status: "expiring",
    expireAt: "2026-07-04T00:00:00Z",
    groups: ["g-design", "g-notion"],
    credential: {
      password: "needs-update",
      passkeys: 0,
      totp: false,
      backupCodes: 0,
      unixCredential: false,
      sshKeys: 1,
      radiusPassword: false,
    },
    unix: {
      gidNumber: null,
      shell: "",
      credentialSet: false,
    },
    lastAuth: "2026-05-28 18:30",
  },
  {
    id: "u-sam",
    username: "sam",
    displayName: "Sam Rivera",
    legalName: "Samuel Rivera",
    email: "sam@aster.example",
    status: "locked",
    groups: ["g-contractors"],
    credential: {
      password: "missing",
      passkeys: 0,
      totp: false,
      backupCodes: 0,
      unixCredential: false,
      sshKeys: 0,
      radiusPassword: false,
    },
    unix: {
      gidNumber: null,
      shell: "",
      credentialSet: false,
    },
    lastAuth: "2026-05-19 11:04",
  },
];

export const seedGroups: Group[] = [
  {
    id: "g-admins",
    name: "idm_admins",
    displayName: "Identity administrators",
    description:
      "Can administer Kanidm users, groups, credentials, and supported application configuration.",
    members: ["u-ava"],
    parentGroups: [],
    managedBy: "g-admins",
  },
  {
    id: "g-engineering",
    name: "engineering",
    displayName: "Engineering",
    description: "Product engineering team with development and observability access.",
    members: ["u-ava", "u-mika"],
    parentGroups: [],
    managedBy: "g-admins",
  },
  {
    id: "g-design",
    name: "design",
    displayName: "Design",
    description: "Product design and research team.",
    members: ["u-rin"],
    parentGroups: [],
    managedBy: "g-admins",
  },
  {
    id: "g-grafana",
    name: "app_grafana",
    displayName: "Grafana users",
    description: "Supplemental access group for Grafana OAuth2 login.",
    members: ["u-ava", "u-mika"],
    parentGroups: ["g-engineering"],
    managedBy: "g-admins",
  },
  {
    id: "g-gitea",
    name: "app_gitea",
    displayName: "Gitea users",
    description: "Supplemental access group for Gitea OAuth2 login.",
    members: ["u-mika"],
    parentGroups: ["g-engineering"],
    managedBy: "g-admins",
  },
  {
    id: "g-notion",
    name: "app_docs",
    displayName: "Documentation users",
    description: "Portal access for documentation and notes.",
    members: ["u-rin"],
    parentGroups: ["g-design"],
    managedBy: "g-admins",
  },
  {
    id: "g-contractors",
    name: "contractors",
    displayName: "Contractors",
    description: "Limited access group for external collaborators.",
    members: ["u-sam"],
    parentGroups: [],
    managedBy: "g-admins",
  },
];

export const seedServiceAccounts: ServiceAccount[] = [
  {
    id: "svc-mail-sender",
    name: "mail_sender",
    displayName: "Mail Sender",
    description: "Sends account recovery and credential update mail through Kanidm.",
    managedBy: "g-admins",
    groups: ["g-admins"],
    credential: {
      password: "present",
      apiTokens: 2,
      sshKeys: 1,
      unixCredential: false,
    },
    unix: {
      gidNumber: null,
      shell: "",
      credentialSet: false,
    },
    status: "ready",
  },
  {
    id: "svc-sync-agent",
    name: "sync_agent",
    displayName: "Sync Agent",
    description: "Automation identity for directory synchronization jobs.",
    managedBy: "g-admins",
    groups: ["g-engineering"],
    credential: {
      password: "unknown",
      apiTokens: 1,
      sshKeys: 0,
      unixCredential: true,
    },
    unix: {
      gidNumber: 21010,
      shell: "/usr/sbin/nologin",
      credentialSet: true,
    },
    status: "attention",
  },
];

export const seedApps: Application[] = [
  {
    id: "app-grafana",
    name: "grafana",
    displayName: "Grafana",
    landingUrl: "https://grafana.aster.example",
    imageUrl: "",
    clientType: "confidential",
    redirectUris: ["https://grafana.aster.example/login/generic_oauth"],
    allowedGroups: ["g-grafana", "g-admins"],
    scopes: ["openid", "profile", "email", "groups"],
    status: "ready",
  },
  {
    id: "app-gitea",
    name: "gitea",
    displayName: "Gitea",
    landingUrl: "https://git.aster.example",
    imageUrl: "",
    clientType: "confidential",
    redirectUris: ["https://git.aster.example/user/oauth2/kanidm/callback"],
    allowedGroups: ["g-gitea", "g-admins"],
    scopes: ["openid", "profile", "email"],
    status: "ready",
  },
  {
    id: "app-docs",
    name: "docs",
    displayName: "Knowledge Base",
    landingUrl: "https://docs.aster.example",
    imageUrl: "",
    clientType: "public",
    redirectUris: ["https://docs.aster.example/oauth/callback"],
    allowedGroups: ["g-notion", "g-admins"],
    scopes: ["openid", "profile"],
    status: "attention",
  },
  {
    id: "app-vault",
    name: "vault",
    displayName: "Vault",
    landingUrl: "https://vault.aster.example",
    imageUrl: "",
    clientType: "confidential",
    redirectUris: ["https://vault.aster.example/ui/vault/auth/oidc/callback"],
    allowedGroups: ["g-admins"],
    scopes: ["openid", "profile", "email", "groups"],
    status: "draft",
  },
];

export const initialState: ConsoleState = {
  role: "admin",
  currentUserId: "u-ava",
  branding: defaultBranding,
  people: seedPeople,
  serviceAccounts: seedServiceAccounts,
  groups: seedGroups,
  apps: seedApps,
};
